spring:
  config:
    import:
      - classpath:application-local.yml
      - classpath:application-dev.yml

jwt:
  secret: devdevdevdevdevdevdevdevdevdevdevdev
  expire-in-millis: 1800000

payment:
  providers:
    - name: toss
      secret: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
      url: https://api.tosspayments.com
      connection-timeout-in-seconds: 3
      read-timeout-in-seconds: 31
